In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plots
import math
import ipywidgets as widgets
from IPython.display import display
from datetime import datetime

In [2]:
covid1 = pd.read_csv("covid_data_1.csv")
covid1

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,0.0,0.0,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,0.0,0.0,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44147,NaN,NaN,International,2020-09-12,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44148,NaN,NaN,International,2020-09-13,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44149,NaN,NaN,International,2020-09-14,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44150,NaN,NaN,International,2020-09-15,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44151,NaN,NaN,International,2020-09-16,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
def death_rate_calculator(row):
    total_deaths = row["total_deaths"]
    pos_cases = row["total_cases"]
    if (np.isnan(pos_cases) or (np.isnan(total_deaths))):
        return None
    if ((np.isnan(pos_cases) == 0 )or (np.isnan(total_deaths)) == 0):
        return 0
    else:
        return total_deaths / pos_cases
def pos_rate_calculator(row):
    pos_cases = row["total_cases"]
    total_tests = row["total_tests"]
    if (np.isnan(pos_cases) or (np.isnan(total_tests))):
        return None
    if ((np.isnan(pos_cases) == 0 )or (np.isnan(total_tests)) == 0):
        return 0
    else:
        return pos_cases / total_tests
covid1["death_rate"] = covid1.apply(death_rate_calculator, axis = 1)
covid1["positive_rate"] = covid1.apply(pos_rate_calculator, axis = 1)
covid1

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,death_rate
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,0.0,0.0,NaN,...,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN,0.0
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN,NaN
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,0.0,0.0,0.0,...,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN,0.0
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN,NaN
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44147,NaN,NaN,International,2020-09-12,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
44148,NaN,NaN,International,2020-09-13,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
44149,NaN,NaN,International,2020-09-14,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
44150,NaN,NaN,International,2020-09-15,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
44151,NaN,NaN,International,2020-09-16,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [4]:
covid1.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'death_rate'],
      dtype='object')

In [67]:
column_names = list(covid1)

In [108]:
death_data = ["new_deaths", "new_deaths_per_million", "total_deaths", "total_deaths_per_million", "death_rate"] # add death rate(and cadiovascular deaths?)
cases_data = ["new_cases", "new_cases_per_million", "total_cases", "new_cases_per_million"]
test_data = ["new_tests", "total_tests", "total_tests_per_thousand", "new_tests_per_thousand", "tests_per_case", "positive_rate"] # tests_units(?)
population_data = ["population", "population_density", "median_age", "aged_65_older", "aged_70_older", "gdp_per_capita", "extreme_poverty"]
misc_data = ["diabetes_prevalence", "female_smokers", "male_smokers", "handwashing_facilities", "hospital_beds_per_thousand", "life_expectancy", "human_development_index", "stringency_index"]

In [202]:
large_output = widgets.Output()

dropdown_category = widgets.Dropdown(description = "Category", options = ['death', 'cases', 'test', "population", "misc", "correlations"])
dropdown_location = widgets.Dropdown(description = "Location", options = unique_sorted_values_plus_ALL(covid1.location))

filtered = pd.DataFrame()

def common_filtering(category, locations):
    
    global filtered
    tempcovid = covid1.copy(deep = True)
    filtered = tempcovid
    cols = list(tempcovid)
    large_output.clear_output()
    templist = ['date', 'location']
    
    if locations != ALL:
        filtered = filtered[filtered.location == locations]
        if (category == 'death'):
            data = death_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
        if (category == 'cases'):
            data = cases_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
        if (category == 'test'):
            data = test_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
        if (category == 'population'):
            data = population_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
        if (category == 'misc'):
            data = misc_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
    else:
        if (category == 'death'):
            data = death_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
        if (category == 'cases'):
            data = cases_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
        if (category == 'test'):
            data = test_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
        if (category == 'population'):
            data = population_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
        if (category == 'misc'):
            data = misc_data
            for i in data:
                templist.append(i)
            filtered = filtered[templist]
    
    with large_output:
        display(filtered)
        

def dropdown_category_eventhandler(change):
    common_filtering(change.new, dropdown_location.value)
def dropdown_location_eventhandler(change):
    common_filtering(dropdown_category.value, change.new)
      
dropdown_category.observe(dropdown_category_eventhandler, names='value')
dropdown_location.observe(dropdown_location_eventhandler, names='value')

display(dropdown_category)
display(dropdown_location)

Dropdown(description='Category', options=('death', 'cases', 'test', 'population', 'misc', 'correlations'), val…

Dropdown(description='Location', options=('ALL', 'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'An…

In [206]:
display(large_output)

Output(outputs=({'output_type': 'display_data', 'data': {'text/plain': '           date     location  new_deat…

In [195]:
d1 = widgets.Dropdown(description = "Choose One", options = ['death', 'cases', 'test', "population", "misc", "correlations"])

output_main = widgets.Output()

filtered1 = pd.DataFrame()

def on_change(change):
    global filtered1
    output_main.clear_output()
    tempcovid = covid1.copy(deep = True)
    filtered1 = tempcovid
    cols = list(tempcovid)
    if (change.new == 'death'):
         data1 = death_data
    if (change.new == 'cases'):
        data1 = cases_data
    if (change.new == 'test'):
        data1 = test_data
    if (change.new == 'population'):
        data1 = population_data
    if (change.new == 'misc'):
        data1 = misc_data
    templist = ['date', 'location']
    for i in data1:
        templist.append(i)
    filtered1 = filtered1[templist]
    with output_main:
        display(filtered1)
d1.observe(on_change, names = 'value')
d1.observe(on_change1, names = 'value')
display(d1)

Dropdown(description='Choose One', options=('death', 'cases', 'test', 'population', 'misc', 'correlations'), v…

In [196]:
display(output_main)

Output()

In [178]:
filtered1

Empty DataFrame
Columns: []
Index: []

In [46]:
def dropdown2(previous_third_col):
    if list(filtered)[2] == "new_deaths":
        data = death_data
    if list(filtered)[2] == "new_cases":
        data = cases_data
    if list(filtered)[2] == "new_tests":
        data = test_data
    if list(filtered)[2] == "population":
        data = death_data
    if list(filtered)[2] == "diabetes_prevalence":
        data = death_data
drp = widgets.Dropdown(description = "Choose One", options = ['death', 'cases', 'test', "population", "misc", "correlations"])

output_value = widgets.Output()

def on_change1(change):
    data1 = death_data
    output_value.clear_output()
    with output_value:
        if (change.new == 'death'):
            data1 = death_data
        if (change.new == 'cases'):
            data1 = cases_data
        if (change.new == 'test'):
            data1 = test_data
        if (change.new == 'population'):
            data1 = population_data
        if (change.new == 'misc'):
            data1 = misc_data
#     if (change.new == 'correlation'):
#         data1 = death_data
        d2 = widgets.Dropdown(description = change.new, options = data1)
        d2.observe(on_change1, names= 'value')
        display(d2)
drp.observe(on_change1, names = 'value')
display(drp)

Dropdown(description='Choose One', options=('death', 'cases', 'test', 'population', 'misc', 'correlations'), v…

In [47]:
display(output_value)

Output()

In [34]:
d1.value

'misc'

In [9]:
ALL = 'ALL'
def unique_sorted_values_plus_ALL(array):
    unique = array.unique().tolist()
    unique.sort()
    unique.insert(0, ALL)
    return unique

Today = 'Today'
def unique_sorted_values_plus_today(array):
    unique = array.unique().tolist()
    unique.sort(reverse = True)
    unique.insert(0, Today)
    return unique

In [10]:
large_output = widgets.output()

def dropdown_creator(value):
    
dropdown_location = widgets.Dropdown(options = unique_sorted_values_plus_ALL(covid1.location))
dropdown_date1 = widgets.Dropdown(options = unique_sorted_values_plus_ALL(covid1.date))
dropdown_date2 = widgets.Dropdown(options = unique_sorted_values_plus_ALL(covid1.date))

def common_filtering(year, purpose):
    output.clear_output()
    
    if (year == ALL) & (purpose == ALL):
        common_filter = df_london
    elif (year == ALL):
        common_filter = df_london[df_london.purpose == purpose]
    elif (purpose == ALL):
        common_filter = df_london[df_london.year == year]
    else:
        common_filter = df_london[(df_london.year == year) & 
                                  (df_london.purpose == purpose)]
    
    with output:
        display(common_filter)

def dropdown_location_eventhandler(change):
    output_location.clear_output()
    with output_location:
        if (change.new == ALL):
            display(covid1)
        else:
            display((covid1[covid1.location == change.new]).head(10))
dropdown_location.observe(dropdown_location_eventhandler, names = 'value')
display(dropdown_location)

Dropdown(options=('ALL', 'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Anguilla', 'Antigua and Ba…

In [11]:
display(output_location)

Output()

In [12]:
print(datetime.today().strftime('%Y-%m-%d'))

2020-09-25

In [18]:
now = pd.to_datetime('now')
last2 = now - pd.DateOffset(months=1)
covid1[covid1.date >= str(last2)]
print(now)

2020-09-25 17:25:42.574696

In [30]:
unique_sorted_values_plus_today(covid1.date)

['Today',
 '2020-09-16',
 '2020-09-15',
 '2020-09-14',
 '2020-09-13',
 '2020-09-12',
 '2020-09-11',
 '2020-09-10',
 '2020-09-09',
 '2020-09-08',
 '2020-09-07',
 '2020-09-06',
 '2020-09-05',
 '2020-09-04',
 '2020-09-03',
 '2020-09-02',
 '2020-09-01',
 '2020-08-31',
 '2020-08-30',
 '2020-08-29',
 '2020-08-28',
 '2020-08-27',
 '2020-08-26',
 '2020-08-25',
 '2020-08-24',
 '2020-08-23',
 '2020-08-22',
 '2020-08-21',
 '2020-08-20',
 '2020-08-19',
 '2020-08-18',
 '2020-08-17',
 '2020-08-16',
 '2020-08-15',
 '2020-08-14',
 '2020-08-13',
 '2020-08-12',
 '2020-08-11',
 '2020-08-10',
 '2020-08-09',
 '2020-08-08',
 '2020-08-07',
 '2020-08-06',
 '2020-08-05',
 '2020-08-04',
 '2020-08-03',
 '2020-08-02',
 '2020-08-01',
 '2020-07-31',
 '2020-07-30',
 '2020-07-29',
 '2020-07-28',
 '2020-07-27',
 '2020-07-26',
 '2020-07-25',
 '2020-07-24',
 '2020-07-23',
 '2020-07-22',
 '2020-07-21',
 '2020-07-20',
 '2020-07-19',
 '2020-07-18',
 '2020-07-17',
 '2020-07-16',
 '2020-07-15',
 '2020-07-14',
 '2020-07-13',
 '2020-07-12',
 '2020-07-11',
 '2020-07-10',
 '2020-07-09',
 '2020-07-08',
 '2020-07-07',
 '2020-07-06',
 '2020-07-05',
 '2020-07-04',
 '2020-07-03',
 '2020-07-02',
 '2020-07-01',
 '2020-06-30',
 '2020-06-29',
 '2020-06-28',
 '2020-06-27',
 '2020-06-26',
 '2020-06-25',
 '2020-06-24',
 '2020-06-23',
 '2020-06-22',
 '2020-06-21',
 '2020-06-20',
 '2020-06-19',
 '2020-06-18',
 '2020-06-17',
 '2020-06-16',
 '2020-06-15',
 '2020-06-14',
 '2020-06-13',
 '2020-06-12',
 '2020-06-11',
 '2020-06-10',
 '2020-06-09',
 '2020-06-08',
 '2020-06-07',
 '2020-06-06',
 '2020-06-05',
 '2020-06-04',
 '2020-06-03',
 '2020-06-02',
 '2020-06-01',
 '2020-05-31',
 '2020-05-30',
 '2020-05-29',
 '2020-05-28',
 '2020-05-27',
 '2020-05-26',
 '2020-05-25',
 '2020-05-24',
 '2020-05-23',
 '2020-05-22',
 '2020-05-21',
 '2020-05-20',
 '2020-05-19',
 '2020-05-18',
 '2020-05-17',
 '2020-05-16',
 '2020-05-15',
 '2020-05-14',
 '2020-05-13',
 '2020-05-12',
 '2020-05-11',
 '2020-05-10',
 '2020-05-09',
 '2020-05-08',
 '2020-05-07',
 '2020-05-06',
 '2020-05-05',
 '2020-05-04',
 '2020-05-03',
 '2020-05-02',
 '2020-05-01',
 '2020-04-30',
 '2020-04-29',
 '2020-04-28',
 '2020-04-27',
 '2020-04-26',
 '2020-04-25',
 '2020-04-24',
 '2020-04-23',
 '2020-04-22',
 '2020-04-21',
 '2020-04-20',
 '2020-04-19',
 '2020-04-18',
 '2020-04-17',
 '2020-04-16',
 '2020-04-15',
 '2020-04-14',
 '2020-04-13',
 '2020-04-12',
 '2020-04-11',
 '2020-04-10',
 '2020-04-09',
 '2020-04-08',
 '2020-04-07',
 '2020-04-06',
 '2020-04-05',
 '2020-04-04',
 '2020-04-03',
 '2020-04-02',
 '2020-04-01',
 '2020-03-31',
 '2020-03-30',
 '2020-03-29',
 '2020-03-28',
 '2020-03-27',
 '2020-03-26',
 '2020-03-25',
 '2020-03-24',
 '2020-03-23',
 '2020-03-22',
 '2020-03-21',
 '2020-03-20',
 '2020-03-19',
 '2020-03-18',
 '2020-03-17',
 '2020-03-16',
 '2020-03-15',
 '2020-03-14',
 '2020-03-13',
 '2020-03-12',
 '2020-03-11',
 '2020-03-10',
 '2020-03-09',
 '2020-03-08',
 '2020-03-07',
 '2020-03-06',
 '2020-03-05',
 '2020-03-04',
 '2020-03-03',
 '2020-03-02',
 '2020-03-01',
 '2020-02-29',
 '2020-02-28',
 '2020-02-27',
 '2020-02-26',
 '2020-02-25',
 '2020-02-24',
 '2020-02-23',
 '2020-02-22',
 '2020-02-21',
 '2020-02-20',
 '2020-02-19',
 '2020-02-18',
 '2020-02-17',
 '2020-02-16',
 '2020-02-15',
 '2020-02-14',
 '2020-02-13',
 '2020-02-12',
 '2020-02-11',
 '2020-02-10',
 '2020-02-09',
 '2020-02-08',
 '2020-02-07',
 '2020-02-06',
 '2020-02-05',
 '2020-02-04',
 '2020-02-03',
 '2020-02-02',
 '2020-02-01',
 '2020-01-31',
 '2020-01-30',
 '2020-01-29',
 '2020-01-28',
 '2020-01-27',
 '2020-01-26',
 '2020-01-25',
 '2020-01-24',
 '2020-01-23',
 '2020-01-22',
 '2020-01-21',
 '2020-01-20',
 '2020-01-19',
 '2020-01-18',
 '2020-01-17',
 '2020-01-16',
 '2020-01-15',
 '2020-01-14',
 '2020-01-13',
 '2020-01-12',
 '2020-01-11',
 '2020-01-10',
 '2020-01-09',
 '2020-01-08',
 '2020-01-07',
 '2020-01-06',
 '2020-01-05',
 '2020-01-04',
 '2020-01-03',
 '2020-01-02',
 '2020-01-01',
 '2019-12-31']